Siva Reddy | Publish SNOMED Specific clinic config docker image

diff --git a/.github/workflows/build_upload.yml b/.github/workflows/build_upload.yml
--- a/.github/workflows/build_upload.yml
+++ b/.github/workflows/build_upload.yml
@@ -2,8 +2,8 @@ name: Build and Upload
 on:
   push:
     branches:
-      - main
-      - 'release-*'
+      - snomed-master
+      - 'snomed-release-*'
     tags:
       - '[0-9]+.[0-9]+.[0-9]+'
     paths-ignore:
@@ -11,21 +11,14 @@ on:
   workflow_dispatch:
 
 jobs:
-  build-publish-docker-helm:
-    name: Build & Publish Docker Image & Helm Chart
+  build-publish-docker:
+    name: Build & Publish Docker Image
     runs-on: ubuntu-latest
-    env:
-      HELM_CHART_PATH: package/helm/clinic-config
     steps:
       - uses: actions/checkout@v2
-      - name: Set env.ARTIFACT_VERSION
-        run: |
-          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
-          ./setArtifactVersion.sh
-          rm setArtifactVersion.sh
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
-      - name: Set up Docker Buildx
+      - name: Set up Docker Build
         uses: docker/setup-buildx-action@v2
       - name: Docker - Login
         uses: docker/login-action@v2
@@ -39,46 +32,26 @@ jobs:
           file: package/docker/Dockerfile
           platforms: linux/amd64,linux/arm64
           push: true
-          tags: bahmni/clinic-config:${{env.ARTIFACT_VERSION}},bahmni/clinic-config:latest
-      - name: Pull Bahmni Default Config Helm Chart
+          tags: bahmni/clinic-config:snomed-${{ github.run_number }},bahmni/clinic-config:snomed-latest
+
+  trigger:
+    name: Trigger Deployment Workflow to SNOMED Dev Environment
+    needs:
+      - build-publish-docker
+    runs-on: ubuntu-latest
+    env:
+      ORG_NAME: Bahmni
+      REPOSITORY_NAME: snomed-bahmni-docker
+      ENVIRONMENT: dev
+    steps:
+      - name: Create repository_dispatch
         run: |
-          helm pull default-config --repo https://bahmni.github.io/helm-charts --devel --untar --untardir package/helm
-          mv package/helm/default-config/ package/helm/clinic-config/
-      - name: Update Chart values
-        run: |
-          yq --inplace '.image.repository = "bahmni"' $HELM_CHART_PATH/values.yaml
-          yq --inplace '.image.name = "clinic-config"' $HELM_CHART_PATH/values.yaml
-          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
-          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml
-          yq --inplace '.name = "clinic-config"' $HELM_CHART_PATH/Chart.yaml
-          yq --inplace '.description = "Helm chart for clinic-config of bahmni"' $HELM_CHART_PATH/Chart.yaml
+          trigger_result=$(curl -s -o trigger_response.txt -w "%{http_code}" -X POST -H "Accept: application/vnd.github.v3+json" -H 'authorization: Bearer ${{ secrets.BAHMNI_PAT }}' https://api.github.com/repos/${ORG_NAME}/${REPOSITORY_NAME}/actions/workflows/snomed-deploy.yml/dispatches -d '{"ref":"snomed-master","inputs":{"environment":"'"${ENVIRONMENT}"'"}}')
+          if [ $trigger_result == 204 ];then
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Success"
+          else
+            echo "Trigger to $ORG_NAME/$REPOSITORY_NAME Failed"
+            cat trigger_response.txt
+            exit 1
+          fi
 
-      - name: Helm Lint
-        run: helm lint $HELM_CHART_PATH
-
-      - name: Helm Package
-        run: helm package $HELM_CHART_PATH
-
-      - name: Helm - Checkout Charts Repository
-        uses: actions/checkout@v2
-        with:
-          repository: bahmni/helm-charts
-          ref: gh-pages
-          path: helm-charts
-          persist-credentials: false
-
-      - name: Helm - Copy chart
-        run: mkdir -p helm-charts/clinic-config/ && cp clinic-config-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/clinic-config/
-
-      - name: Helm - reIndex
-        working-directory: helm-charts/
-        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/  .
-
-      - name: Helm - Publish Chart
-        working-directory: helm-charts/
-        run: |
-          git config user.name ${{ secrets.BAHMNI_USERNAME}}
-          git config user.email ${{ secrets.BAHMNI_EMAIL}}
-          git add .
-          git commit -m "Release of clinic-config-${{ env.ARTIFACT_VERSION }}"
-          git push 'https://${{ secrets.BAHMNI_USERNAME}}:${{ secrets.BAHMNI_PAT}}@github.com/bahmni/helm-charts.git' gh-pages
